(cl:in-package robot_control-msg)
(cl:export '(MODE_CHANGED-VAL
          MODE_CHANGED
          SIGN_MODE_CHANGED-VAL
          SIGN_MODE_CHANGED
          TEST_STARTED-VAL
          TEST_STARTED
          DEPTH_FIXED-VAL
          DEPTH_FIXED
          RECORD_INIT-VAL
          RECORD_INIT
          MODE_NAME-VAL
          MODE_NAME
          SIGN_MODE_NAME-VAL
          SIGN_MODE_NAME
          SUBJECT_NAME-VAL
          SUBJECT_NAME
          SIMULATOR_NAME-VAL
          SIMULATOR_NAME
          TEST_SHAPE-VAL
          TEST_SHAPE
          DEPTH-VAL
          DEPTH
          MAX_ANGLE-VAL
          MAX_ANGLE
          LATEST_RMSE-VAL
          LATEST_RMSE
          INFO-VAL
          INFO
))